### ISSUE TITLE
vcn cannot be used with read only directories using the dir:// scheme

### ISSUE THREAD

**Issue by ivan-w** [vchain-us/vcn#45]
when using for example "vcn authenticate dir://some directory" and that directory is read only, vcn fails because it is trying to create a default .vcnignore file, which is impossible since the directory is read only.

For example :  
```
ivan@db08:~/vChain/vcn-cr/dist$ ./vcn-v0.6.1-linux-amd64 v dir:///etc
Error: open /etc/.vcnignore: permission denied

```

**Comment by ivan-w** [comment]
For reference 
The issue is related to the initIgnoreFile function and the call to 
f, err := os.OpenFile(filename, os.O_RDWR|os.O_CREATE|os.O_EXCL, 0644)
in pkg/extractor/dir/vcnignore.go

**Comment by ivan-w** [comment]
Here is what I suggest : 

- if a .vcnignore exists at the root level of the directory, use it
- if there is no .vcnignore in the directory, instead of a using nullMatcher (a matcher that is always false), create one based on the one we provide in the initIgnoreFile function (set data to DefaultIgnoreFileContent if the file doesn't exist instead of reading it)
- Provide a option flag to instruct vcn to write a .vcnignore file (invoke initIgnoreFile) to the base directory should the user wish it
This way : 
- vcn dir:// scheme can be used on Read Only directories which do not have a .vcnignore
- vcn does not pollute the user target directory in ways the user had not foreseen
- vcn can write the hardcoded .vcnignore upon request for inspection and/or modification should the user elect to do so.

**Comment by leogr** [comment]
Hi @ivan-w,

thanks for you contributions! 

Here my thoughts: 

> * if there is no .vcnignore in the directory, instead of a using nullMatcher (a matcher that is always false), create one based on the one we provide in the initIgnoreFile function (set data to DefaultIgnoreFileContent if the file doesn't exist instead of reading it)

vcn cannot use a default ignore list without writing/reading it to/from the target directory because either:
1. `.vcnignore` is part of the digested input, indeed distinct ignore lists would produce distinct views on the dir tree, that means that if the ignore list is different then dir is not authentic anymore;
2. the default list can change over time, so it needed to store the `.vcnignore` used at time of notarization;

> * Provide a option flag to instruct vcn to write a .vcnignore file (invoke initIgnoreFile) to the base directory should the user wish it
Maybe we can:
- provide an option to instruct vcn to do NOT write (so the default behavior will not change)
- when notarizing a Read Only dir just stop the execution and inform the user that the flag can be used to overcome that
- when authenticate a dir which does not have a `.vcnignore` the `nullMatcher` is still used

This way would not introduce any breaking change, and Read Only dirs would work too.

Let me know what you think about my alternative proposal.

**Comment by ivan-w** [comment]
Thinking out loud here, don't take anything wrong..

I am a little worried that even doing a simple "authenticate' (which should be an entirely read-only operation) is going to change the target... Actually altering the target altogether.. but anyways...

Also, if the .vcnignore is included in the hash (not ignoring itself) when making an exact copy of a directory - notarizing it once with a certain version of vcn, then later taking the second copy of the exact same directory and  authenticating it with another version of vcn may ALSO result in different results if the hard-coded default template is changed - although the contents of the directories were entirely identical in origin.

Notarizing/Authenticating a read only directory vs a read/write directory may also result in different results even if the original contents are strictly identical (except for permissions) in ways unsuspecting to the user if the R/W directory gets it and the R/O directory doesn't.

**Comment by leogr** [comment]
> I am a little worried that even doing a simple "authenticate' (which should be an entirely read-only operation) is going to change the target... Actually altering the target altogether.. but anyways...

I agree, indeed it would be better to do not create `.vcnignore` when "authenticating".
So we could create it only when "notarizing", but only if that had no side effect (we need to double check this).
 
> Also, if the .vcnignore is included in the hash (not ignoring itself) when making an exact copy of a directory - notarizing it once with a certain version of vcn, then later taking the second copy of the exact same directory and authenticating it with another version of vcn may ALSO result in different results if the hard-coded default template is changed - although the contents of the directories were entirely identical in origin.

 Atm, `.vcnignore` is always created when "notarizing" and becomes part of the directory content (ofc notarization will fail if R/O).

Now, let's assume:
 - we provide an option to instruct vcn to do not write it (e.g. to manually overcome the R/O dir issue), in this case an empty list should be assumed (i.e. `nullMatcher`)
 - `.vcnignore` is not created when "authenticating" (as I wrote above)

With these assumptions: 
- if the `.vcnignore` was created then the "authentication" will work only if the original `.vcnignore` is inside the targeted dir (maybe this is a requirement users can live with?)
 - if the `.vcnignore` was NOT created (by using the option we provide) then the "authentication" will still work (because an empty list is assumed)
- if the default list changed, then the two cases above are not affected (authentication will only use the `.vcnignore` created at notarization time, if any, otherwise an empty list)


> Notarizing/Authenticating a read only directory vs a read/write directory may also result in different results even if the original contents are strictly identical (except for permissions) in ways unsuspecting to the user if the R/W directory gets it and the R/O directory doesn't.

The solution above should avoid any unexpected behavior (ofc, the auditor still has to know the `.vcnignore` requirements).

Let me know what you think about.

**Comment by leogr** [comment]
Hi @ivan-w ,

Within the [0.7.0 branch](https://github.com/vchain-us/vcn/tree/0.7.0) I've added functional options for extractors and instructed vcn to do not create `.vcnignore` when authenticating. 

That solves the RO issue for verification only, but I'm pretty sure that functional options will make easier the fix for the notarization too.

**Comment by ivan-w** [comment]
I'll look into it - but it's probably the right path !
