### ISSUE TITLE
vcn not working

### ISSUE THREAD

**Issue by moshix** [vchain-us/vcn#85]
What's going on here??

moshe@jumpserver:~$ vcn083 n dir:///debian
Error: open /debian: no such file or directory
moshe@jumpserver:~$ vcn083 n dir://debian
Error: open /home/moshe/debian/.vcnignore: permission denied
moshe@jumpserver:~$ sudo vcn083 n dir:///debian
sudo: unable to resolve host jumpserver
Error: open /debian: no such file or directory
moshe@jumpserver:~$

**Comment by vchain-us-mgmt** [comment]
1) 
the permission error is caused by a former notarization of the home/moshe/debian directory using elevated permissions (sudo). As it creates a .vcnignore file with the elevated permissions that can't be accessed when notarizing with a normal user.

sudo chown -R moshe /home/moshe/debian should do the trick.

2)
the resolve error, comes from a missing entry in your /etc/hosts
